#!/usr/bin/env bash

NSD_DEVICE_DIR=/var/mmfs/etc
NSD_DEVICE_FILE=$${NSD_DEVICE_DIR}/nsddevices

# Prepare nsddevices script so Storage Scale can discover the links
# that are created
if [ ! -d "$${NSD_DEVICE_DIR}" ];
then
   mkdir -p "$${NSD_DEVICE_DIR}"
fi

echo "#!/bin/ksh" > $${NSD_DEVICE_FILE}
echo "# Generated by IBM Storage Scale deployment." >> $${NSD_DEVICE_FILE}
echo "echo \"/dev/nvme[0-9]\+n1$ generic\"" >> $${NSD_DEVICE_FILE}
echo "# Bypass the NSD device discovery" >> $${NSD_DEVICE_FILE}
echo "return 0" >> $${NSD_DEVICE_FILE}
chmod u+x $${NSD_DEVICE_FILE}
