---

- name: Check CES IPs and create route in ibm cloud
  hosts: scale_nodes
  tasks:
  - name: Check ips for ces nodes
    shell: "/usr/lpp/mmfs/bin/mmces address list -Y | tail -n +2 | awk -F: '{print $7, $8}' | sort -k2 | awk '{print $1}'"
    register: ces_ips
    when: is_admin_node | default(false) == true
    run_once: true

  - name: Debug the ces ips sorted based on hostname
    debug:
      var: ces_ips.stdout_lines
    when: is_admin_node | default(false) == true

  - name: Save the output to a file on the remote machine
    copy:
      content: "{{ ces_ips.stdout_lines }}"
      dest: "/tmp/ces_ips.txt"
    when: is_admin_node | default(false) == true

  - name: Fetch the file to the local machine
    fetch:
      src: "/tmp/ces_ips.txt"
      dest: "/tmp/ces_ips.txt"
      flat: yes
    when: is_admin_node | default(false) == true

  - name: Delete the file on the remote machine
    file:
      path: "/tmp/ces_ips.txt"
      state: absent
    when: is_admin_node | default(false) == true
